language: go
go: 1.3

install:
  go get -v -tags='appengine appenginevm' ./... && hg clone https://code.google.com/p/appengine-go/ $GOPATH/appengine

script:
  go test -v -tags='appengine appenginevm' ./... && go build -v -tags='appengine'
